#!/bin/sh
# One-shot installer for the Rig Kontrol 3 MIDI bridge.
# - installs libusb (Homebrew)
# - builds an isolated virtualenv with the Python deps
# - drops a `rig-kontroller` launch command into ~/.local/bin
# Re-runnable; safe to run again to repair the install.
set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
echo "Installing Rig Kontrol 3 bridge from: $DIR"

# 1. System USB library (no-op if already present)
if command -v brew >/dev/null 2>&1; then
    brew list libusb >/dev/null 2>&1 || brew install libusb
else
    echo "WARNING: Homebrew not found — install libusb manually so pyusb can find a backend."
fi

# 2. Isolated virtualenv + Python deps
python3 -m venv "$DIR/.venv"
"$DIR/.venv/bin/pip" install --quiet --upgrade pip
"$DIR/.venv/bin/pip" install --quiet -r "$DIR/requirements.txt"

# 3. Launch command on PATH
mkdir -p "$HOME/.local/bin"
cat > "$HOME/.local/bin/rig-kontroller" <<EOF
#!/bin/sh
# Auto-generated by install.sh — launches the bridge via its own virtualenv.
exec "$DIR/.venv/bin/python" "$DIR/rig_kontroller.py" "\$@"
EOF
chmod +x "$HOME/.local/bin/rig-kontroller"

echo
echo "Done. The 'rig-kontroller' command is installed."
case ":$PATH:" in
    *":$HOME/.local/bin:"*) echo "Run it from anywhere:  rig-kontroller" ;;
    *) echo "NOTE: add ~/.local/bin to your PATH, e.g. in ~/.zshrc:"
       echo '      export PATH="$HOME/.local/bin:$PATH"' ;;
esac
